### ISSUE TITLE
Datasource provision sometimes fails

### ISSUE THREAD

**Issue by Ikuze** [go-graphite/docker-go-graphite#3]
Hello,

First off, very good job, congratulations.

I am having some problems with the provision of the datasource. In some machines the provision is done properly and in other machines the provision fails and the datasource is not created.

I have been able to reproduce the problem by setting a lower sleep time in the Dockerfile grafana installation. If you set "sleep 1" instead of 5 you will see that grafana has not the datasource provisioned once it is up.

The Dockerfile copies the provision yaml to /etc/grafana/provisioning/datasources/carbonapi.yaml, but actually, once the grafana-server is started by the run script, the  homepath is set to 

--homepath=/usr/share/grafana/

And the configuration file says that the provisioning file should be in /usr/share/grafana/conf/provisioning/...

In order to make it work I made some changes. I have submitted those changes as a pull request, just in case you agree with them and want to merge them.

Thank you very much for sharing this, and BR.

**Comment by deniszh** [comment]
Hi  @Ikuze ,

Ooh, sorry, I should renew this repo a bit - upgrade versions and probably migrate to alpine.

Did you test your patch - is it make successful provisioning and Grafana works fine? Even after container restart?

**Comment by Ikuze** [comment]
Hello,

Yes I am using my patch with no problem. The datasource is provisioned properly and there is no problem after the container restart, no matter if the machine is fast or slow.

I guess that since you are not provissioning the datasource with curl anymore, the service restart+sleep is not needed.

BR, and thank you again for sharing this repo.

**Comment by deniszh** [comment]
New layout should work fine, see #8
